import React, {useEffect, useMemo, useState} from "react";
import {createRoot} from "react-dom/client";
import {
  Waves, Menu, X, LogIn, LogOut, ShieldCheck, Building2, Users, CalendarDays,
  Search, Plus, Edit3, Trash2, History, CheckCircle2, Clock3, XCircle,
  MapPin, Phone, Mail, ChevronRight, Upload, Save, UserCheck, UserX,
  Settings2, ClipboardCheck, LayoutDashboard, Eye, LockKeyhole, ArrowRight,
  RefreshCw
} from "lucide-react";
import {supabase} from "./supabase";
import "./styles.css";

const emptyCollege={name:"",logo_url:"",location:""};
const emptyContact={hod_name:"",hod_phone:"",hod_email:"",coordinator_name:"",coordinator_phone:"",coordinator_email:"",private_notes:""};
const emptyEvent={name:"",logo_url:"",description:"",current_heads:"",rules:""};
const emptySlot={event_id:"",event_date:"",start_time:"",end_time:"",venue:""};

const seedEvents=[
 ["CodeWave","Coding","Number of participants: 2.\nParticipants may use C, Java, or Python.\nBasic knowledge of Data Structures & Algorithms is expected.\nInternet, AI tools, and external assistance are not allowed.\nRound-specific rules will be announced before each round.\nThis is a solo event, and each participant will compete individually.\nParticipants are expected to maintain professional and respectful conduct throughout the event.\nParticipants must follow organizer instructions.\nCheating, unfair practice, or misconduct will result in disqualification.\nJudges and organizers decisions are final.","Hayas : 7483989780\nShashidhara : 7760770725"],
 ["Leviathan","IT Manager","This is a solo event, and each participant will compete individually.\nParticipants are expected to maintain professional and respectful conduct throughout the event.\nParticipants must follow organizer instructions.\nCheating, unfair practice, or misconduct will result in disqualification.\nThe decision of the judges and organizers will be final.","Jathin : 6364058375\nHasth : 7338371775"],
 ["Coral Canvas","Web Design","Participants: 2 participants per team.\nSkills: Knowledge of HTML, CSS & JavaScript is required.\nTasks: Rounds and design tasks will be given on the spot.\nElectronic gadgets are not allowed.\nRules and decisions of the organizers will be final.","Swasthik : 8951192848\nUdith : 8088575178"],
 ["Aqua Byte","IT Quiz","Participants: Each team shall consist of 2 participants.\nTopics: General Knowledge, Technical Knowledge, Programming, IT, Computer Science, and other IT-related topics.\nMobile phones, smartwatches, and electronic gadgets are strictly prohibited.\nJudges decision shall be final and binding.\nMalpractice or violation of rules will lead to disqualification.","Thushar : 7019512573\nPrathiksha : 6363428734"],
 ["Aquaverse","Tech Talk","Each participant will compete individually.\nThe topic for each round will be disclosed a few minutes before it begins.\nJudges decisions are final and binding.\nParticipants must maintain respectful and professional behaviour.\nOffensive language, inappropriate content, cheating, or disrespectful behaviour will lead to immediate disqualification.","Krupa : 8296612368\nHruthika : 9353480749"],
 ["The Mega Pitch","Startup Event","Number of participants: 2.\nParticipants must bring their own laptops.\nThe details of each round will be disclosed on the spot.\nThe judges decision will be final.","Sumanth : 8748059243\nShahavez : 7349342520"],
 ["Tide & Tailor","Fashion Show","Team & Theme: Each team must have 2 members and follow a corporate/professional theme.\nOutfits: formal, business casual, modern office, or power-dressing styles.\nStage Performance: 2+1 minutes on stage; confidence, posture, walking style, and presentation will be judged.\nOutfits must be college-event appropriate and professional. Submit music in advance and report before assigned time.","Prapthi : 9632081932\nPrathiksha : 9483505763"],
 ["Submarine","Photography & Videography","Participants & Equipment: 1 participant per entry. DSLR/mirrorless cameras and smartphones are allowed.\nAll content must be captured within the NMAMIT Nitte campus.\nAI-generated content, stock/pre-shot content, or AI-based replacements are strictly prohibited.\nAll submitted content must be captured during the event and must be the participant's own work.","Goutam : 9242288471\nBhargavi : 9632081787"],
 ["Ocean Enigma","Surprise Event","Team: Each team consists of 2 participants.\nMystery: Event details will be revealed only at the venue.\nSurprise bonus challenges may appear at any time.\nElectronic devices are not allowed.\nSome tasks are time-based; fair play and sportsmanship are required, and judges decisions are final.","Sameeksha : 7676292225\nDheemanth : 9480463974"],
 ["Abyss Arena","Gaming — BGMI","Team: Each team must consist of 4 players.\nEmulators, iPads, and triggers are not allowed; players must bring their own mobile devices and accessories.\nDevices must support the latest game version, with required maps downloaded.\nPlayers should have their own internet connection as a backup.\nMisconduct or unfair play will lead to disqualification, and organizers decisions are final.","Jithesh : 7619168599\nKeerthan : 8792839166"]
];

const scheduleSeed=[
 ["2026-09-17","08:00","09:00","Registration & Breakfast","Auditorium Foyer"],
 ["2026-09-17","09:00","11:00","Inaugural Ceremony","Sambhram Auditorium"],
 ["2026-09-17","11:00","12:00","Tide & Tailor","Sambhram Auditorium"],
 ["2026-09-17","11:00","12:00","Coral Canvas","MCA Lab 1"],
 ["2026-09-17","11:00","13:00","CodeWave","MCA Lab 2"],
 ["2026-09-17","11:00","16:00","Leviathan","Netravathi Hall"],
 ["2026-09-17","11:00","16:00","Submarine","Sowparnika"],
 ["2026-09-17","12:15","13:15","Ocean Enigma","LH 402"],
 ["2026-09-17","13:00","15:00","The Mega Pitch","Shambavi Hall"],
 ["2026-09-17","13:00","14:30","Aquaverse","Palguni Hall"],
 ["2026-09-17","13:00","16:00","Abyss Arena","MCA Lab 3 & MCA Lab 4"],
 ["2026-09-17","14:00","16:00","Ocean Enigma","Sambhram Auditorium"],
 ["2026-09-17","14:45","16:15","Coral Canvas","MCA Lab 1"],
 ["2026-09-17","14:45","16:15","CodeWave","MCA Lab 2"],
 ["2026-09-17","15:15","16:15","Aqua Byte","Robotics Lab"],
 ["2026-09-18","09:00","10:00","Aqua Byte","NC 36"],
 ["2026-09-18","09:00","10:30","Aquaverse","Sambhram Auditorium"],
 ["2026-09-18","09:00","13:00","CodeWave","MCA Lab 2"],
 ["2026-09-18","09:00","13:00","Submarine","Sowparnika"],
 ["2026-09-18","09:00","11:45","Leviathan","Netravathi Hall"],
 ["2026-09-18","10:15","11:45","The Mega Pitch","Shambavi Hall"],
 ["2026-09-18","10:15","13:30","Coral Canvas","MCA Lab 1"],
 ["2026-09-18","10:15","13:30","Abyss Arena","MCA Lab 4"],
 ["2026-09-18","10:15","13:30","Ocean Enigma","LH 402"],
 ["2026-09-18","12:00","13:30","Aqua Byte","Sambhram Auditorium"],
 ["2026-09-18","13:30","15:00","Leviathan","Sambhram / Sowparnika"],
 ["2026-09-18","15:00","","Valedictory Ceremony","Sambhram Auditorium"]
];

export default function App(){
 const [page,setPage]=useState("home"),[menu,setMenu]=useState(false),[session,setSession]=useState(null),[profile,setProfile]=useState(null);
 const [colleges,setColleges]=useState([]),[events,setEvents]=useState([]),[students,setStudents]=useState([]),[slots,setSlots]=useState([]),[participation,setParticipation]=useState([]),[attendance,setAttendance]=useState([]);
 const [query,setQuery]=useState(""),[selected,setSelected]=useState(null),[privateData,setPrivateData]=useState(null),[toast,setToast]=useState("");
 const [admin,setAdmin]=useState(false),[auth,setAuth]=useState({email:"",password:""}),[authError,setAuthError]=useState("");
 const [refreshing,setRefreshing]=useState(false);

 useEffect(()=>{loadPublic();supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)loadPrivate();else{setProfile(null);setPrivateData(null);setAttendance([])}},[session]);

 async function loadPublic(){
   setRefreshing(true);
   const [c,e,p,s,pa]=await Promise.all([
     supabase.from("colleges").select("*").order("name"),
     supabase.from("events").select("*").order("name"),
     supabase.from("participants_public").select("*").order("name"),
     supabase.from("event_schedule").select("*").order("event_date").order("start_time"),
     supabase.from("event_college_participation").select("*")
   ]);
   setColleges(c.data||[]);setEvents(e.data||[]);setStudents(p.data||[]);setSlots(s.data||[]);setParticipation(pa.data||[]);setRefreshing(false);
 }
 async function loadPrivate(){
   const {data:p}=await supabase.from("profiles").select("*").eq("id",session.user.id).maybeSingle();setProfile(p);
   if(p?.role==="authorised"||p?.role==="admin"){
     const [contacts,status,pc,att]=await Promise.all([
       supabase.from("college_contacts").select("*"),supabase.from("college_status").select("*"),
       supabase.from("participant_contacts").select("*"),supabase.from("attendance").select("*")
     ]);
     setPrivateData({contacts:contacts.data||[],status:status.data||[],participantContacts:pc.data||[]});setAttendance(att.data||[]);
   }
 }
 async function reload(){await loadPublic();if(session)await loadPrivate()}
 async function login(e){e.preventDefault();setAuthError("");const {error}=await supabase.auth.signInWithPassword(auth);if(error)setAuthError(error.message);else{setPage("home");setMenu(false)}}
 async function logout(){await supabase.auth.signOut();setAdmin(false)}
 const role=profile?.role;
 const filtered=useMemo(()=>colleges.filter(c=>(c.name+" "+(c.location||"")).toLowerCase().includes(query.toLowerCase())),[colleges,query]);
 const counts=useMemo(()=>({confirmed:privateData?.status.filter(x=>x.status==="confirmed").length||0,pending:privateData?.status.filter(x=>x.status==="pending").length||0,denied:privateData?.status.filter(x=>x.status==="denied").length||0}),[privateData]);
 
 if(page==="login")return <Login auth={auth} setAuth={setAuth} error={authError} login={login} back={()=>setPage("home")}/>;
 return <div className="app">
  <div className="glow g1"/><div className="glow g2"/>
  <header><a className="brand" href="#home" onClick={()=>setPage("home")}><Waves/><span>AQUA<b>DESK</b></span></a><nav className={menu?"open":""}>
   <a href="#home" onClick={()=>{setPage("home");setMenu(false)}}>Home</a><a href="#colleges" onClick={()=>{setPage("colleges");setMenu(false)}}>Colleges</a><a href="#events" onClick={()=>{setPage("events");setMenu(false)}}>Schedule</a>
   {role&&<a href="#ops" onClick={()=>{setPage("ops");setMenu(false)}}>Operations</a>}
   {role==="admin"&&<button onClick={()=>{setAdmin(true);setMenu(false)}}><ShieldCheck size={15}/> Admin</button>}
   {session?<button onClick={logout}><LogOut size={15}/> Logout</button>:<a href="#login" onClick={()=>{setPage("login");setMenu(false)}}><LogIn size={15}/> Login</a>}
  </nav><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>

  {page==="home"&&<Home colleges={colleges} events={events} students={students} slots={slots} setPage={setPage} setSelected={setSelected} />}
  {page==="colleges"&&<Colleges colleges={filtered} query={query} setQuery={setQuery} students={students} setSelected={setSelected}/>} 
  {page==="events"&&<Events events={events} slots={slots}/>} 
  {page==="ops"&&role&&<Operations colleges={colleges} events={events} slots={slots} students={students} participation={participation} attendance={attendance} privateData={privateData} role={role} reload={reload} toast={setToast}/>} 
  {selected&&<CollegeModal college={selected} students={students.filter(s=>s.college_id===selected.id)} privateData={privateData} authorised={!!role} close={()=>setSelected(null)}/>} 
  {admin&&<AdminPanel colleges={colleges} events={events} students={students} slots={slots} participation={participation} close={()=>setAdmin(false)} reload={reload} toast={setToast}/>} 
  {toast&&<div className="toast">{toast}</div>}
  <div className="mobile-actions"><button onClick={()=>setPage("home")}><Waves/><span>Home</span></button><button onClick={()=>setPage("colleges")}><Building2/><span>Colleges</span></button><button onClick={()=>setPage("events")}><CalendarDays/><span>Schedule</span></button>{role?<button onClick={()=>setPage("ops")}><ClipboardCheck/><span>Ops</span></button>:<button onClick={()=>setPage("login")}><LogIn/><span>Login</span></button>}</div>
 </div>
}

function Home({colleges,events,students,slots,setPage,setSelected}){return <main>
 <section className="hero hero-premium"><div className="hero-copy"><span className="eyebrow">SEMAPHORE 2K26 · AQUA DESK</span><h1>The command centre<br/>beneath the <em>surface.</em></h1><p>Explore participating colleges, discover every event, follow the official 17–18 September 2026 schedule, and let authorised teams manage confirmations and live attendance.</p><div className="actions"><button className="primary" onClick={()=>setPage("colleges")}>Explore colleges <ChevronRight size={17}/></button><button className="secondary" onClick={()=>setPage("events")}>Open live schedule</button></div><div className="chips"><span><ShieldCheck/> Secure public + operations layers</span><span><Building2/> {colleges.length} colleges</span><span><Users/> {students.length} participants</span></div></div><div className="hero-visual"><div className="ring r1"/><div className="ring r2"/><div className="ring r3"/><div className="hero-core"><Waves size={62}/><small>SEMAPHORE<br/><b>2K26</b></small></div><div className="float-card"><CalendarDays/><div><b>17—18 SEP</b><span>{slots.length} schedule entries</span></div></div></div></section>
 <section className="strip"><div><b>{colleges.length}</b><span>Participating colleges</span></div><div><b>{students.length}</b><span>Participant names</span></div><div><b>{events.length}</b><span>Official events</span></div><div><b>2</b><span>Event days</span></div></section>
 <section className="section"><div className="section-head"><div><span className="eyebrow">PUBLIC DIRECTORY</span><h2>Who's joining <em>the tide?</em></h2></div><button onClick={()=>setPage("colleges")}>All colleges <ChevronRight size={16}/></button></div><div className="cards">{colleges.slice(0,3).map(c=><CollegeCard key={c.id} c={c} students={students} click={()=>setSelected(c)}/>)}</div></section>
 <section className="schedule-teaser"><div><span className="eyebrow">OFFICIAL TIMETABLE</span><h2>Two days.<br/><em>One current.</em></h2><p>Every slot from the supplied Semaphore 2K26 schedule is structured so the admin can edit it later without changing the page.</p><button className="secondary" onClick={()=>setPage("events")}>View full schedule <ArrowRight size={16}/></button></div><div className="timeline-mini">{slots.slice(0,6).map((s,i)=><div className="timeline-row" key={s.id||i}><span>{s.start_time?.slice(0,5)}{s.end_time?`—${s.end_time.slice(0,5)}`:"+"}</span><b>{s.event_name||"Schedule"}</b><small>{s.venue}</small></div>)}</div></section>
 <section className="event-highlight"><div><span className="eyebrow">EVENT CENTRE</span><h2>Rules, heads<br/>& <em>participation.</em></h2><p>Each event has its own editable description, rules, heads, logo, schedule and participating-college matrix.</p></div><div className="mini-events">{events.slice(0,3).map(e=><div key={e.id}><CalendarDays/><b>{e.name}</b><span>{e.description?.split("\n")[0]||"Event details available"}</span></div>)}</div></section>
 </main>}

function Colleges({colleges,query,setQuery,students,setSelected}){return <main className="section page"><div className="section-head"><div><span className="eyebrow">01 / PUBLIC DIRECTORY</span><h2>Participating <em>colleges.</em></h2><p className="muted">Public view shows names and general location only. Private contacts stay behind authorisation.</p></div><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search college or location"/></div></div><div className="cards">{colleges.map(c=><CollegeCard key={c.id} c={c} students={students} click={()=>setSelected(c)}/>)}</div></main>}
function CollegeCard({c,students,click}){return <button className="college-card" onClick={click}><div className="logo">{c.logo_url?<img src={c.logo_url} alt=""/>:<Building2/>}</div><span>{c.location||"Location pending"}</span><h3>{c.name}</h3><small>{students.filter(s=>s.college_id===c.id).length} participant names listed</small><ChevronRight className="arrow"/></button>}

function CollegeModal({college,students,privateData,authorised,close}){const contact=privateData?.contacts.find(x=>x.college_id===college.id);const status=privateData?.status.find(x=>x.college_id===college.id);return <div className="overlay" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><div className="modal-top"><div className="logo big">{college.logo_url?<img src={college.logo_url} alt=""/>:<Building2/>}</div><div><span className="eyebrow">{college.location}</span><h2>{college.name}</h2>{authorised&&<Status status={status?.status||"pending"}/>}</div></div><h3 className="sub"><Users/> Participant names</h3><div className="names">{students.length?students.map(s=><div key={s.id}><b>{s.name}</b><span>{s.team_name||"Team not specified"}</span></div>):<div className="empty">No participant names listed yet.</div>}</div>{authorised&&<div className="private-box"><h3><LockKeyhole/> Authorised information</h3><div className="detail-grid"><Info label="HOD" value={contact?.hod_name} phone={contact?.hod_phone} email={contact?.hod_email}/><Info label="Student Coordinator" value={contact?.coordinator_name} phone={contact?.coordinator_phone} email={contact?.coordinator_email}/></div><p>{contact?.private_notes||"No private notes."}</p></div>}</div></div>}
function Info({label,value,phone,email}){return <div className="info"><b>{label}</b><strong>{value||"Not added"}</strong>{phone&&<span><Phone size={13}/>{phone}</span>}{email&&<span><Mail size={13}/>{email}</span>}</div>}
function Status({status}){return <span className={`status ${status}`}><i/>{status}</span>}

function Events({events,slots}){return <main className="section page"><div className="section-head"><div><span className="eyebrow">02 / OFFICIAL PROGRAMME</span><h2>Schedule of <em>events.</em></h2><p className="muted">17 and 18 September 2026. This schedule is editable by the Super Admin.</p></div></div><div className="schedule-grid"><DaySchedule date="2026-09-17" title="DAY 01" slots={slots} events={events}/><DaySchedule date="2026-09-18" title="DAY 02" slots={slots} events={events}/></div><div className="event-list">{events.map(e=><article key={e.id}><div className="event-logo">{e.logo_url?<img src={e.logo_url} alt=""/>:<CalendarDays/>}</div><div><span className="eyebrow">EVENT</span><h3>{e.name}</h3><p>{e.description||"Details will be announced."}</p><div className="event-meta"><span><Users/> {e.current_heads?.split("\n").length||0} heads listed</span><span><MapPin/> Schedule linked below</span></div></div><div className="heads"><b>Current heads</b>{(e.current_heads||"Not added").split("\n").map((x,i)=><span key={i}>{x.split(" :")[0].split(" - ")[0]}</span>)}</div></article>)}</div></main>}
function DaySchedule({date,title,slots,events}){const day=slots.filter(s=>s.event_date===date);return <div className="day-card"><div className="day-head"><div><b>{title}</b><span>{new Date(date+"T12:00:00").toLocaleDateString("en-IN",{day:"2-digit",month:"long",year:"numeric"})}</span></div><small>Breakfast 8:00 AM · Lunch 12:00 PM—2:00 PM</small></div><div className="table-head"><span>TIME</span><span>EVENT</span><span>VENUE</span></div>{day.map((s,i)=><div className="schedule-row" key={s.id||i}><span>{fmtTime(s.start_time)} {s.end_time?`— ${fmtTime(s.end_time)}`:"Onwards"}</span><b>{s.event_name||events.find(e=>e.id===s.event_id)?.name||"Event"}</b><span>{s.venue}</span></div>)}</div>}
function fmtTime(v){if(!v)return "";const [h,m]=v.slice(0,5).split(":").map(Number);const ap=h>=12?"PM":"AM";const hh=h%12||12;return `${String(hh).padStart(2,"0")}:${String(m).padStart(2,"0")} ${ap}`}

function Operations({colleges,events,slots,students,participation,attendance,privateData,role,reload,toast}){
 const [selectedSlot,setSelectedSlot]=useState(slots[0]?.id||"");
 useEffect(()=>{if(!selectedSlot&&slots[0])setSelectedSlot(slots[0].id)},[slots,selectedSlot]);
 const slot=slots.find(s=>s.id===selectedSlot);const event=events.find(e=>e.id===slot?.event_id);
 const participatingCollegeIds=new Set(participation.filter(p=>p.event_id===slot?.event_id&&p.participating).map(p=>p.college_id));
 const participants=students.filter(s=>participatingCollegeIds.has(s.college_id));
 async function mark(participantId,status){const {error}=await supabase.from("attendance").upsert({schedule_id:slot.id,participant_id:participantId,status,marked_by:(await supabase.auth.getUser()).data.user?.id,marked_at:new Date().toISOString()},{onConflict:"schedule_id,participant_id"});if(error)toast(error.message);else{toast(`Marked ${status}`);await reload()}}
 return <main className="section page ops-page"><div className="ops-hero"><div><span className="eyebrow">AUTHORISED OPERATIONS</span><h2>Run the room.<br/><em>One roster at a time.</em></h2><p>Choose a live schedule slot and mark participants Present or Absent. Super Admin controls the participating-college matrix.</p></div><div className="ops-badge"><ClipboardCheck/><b>{participants.length}</b><span>people in this slot</span></div></div><div className="ops-toolbar"><select value={selectedSlot} onChange={e=>setSelectedSlot(e.target.value)}>{slots.map(s=><option key={s.id} value={s.id}>{s.event_date} · {fmtTime(s.start_time)} · {s.event_name||events.find(e=>e.id===s.event_id)?.name}</option>)}</select><span>{event?.name||"Select a schedule slot"} · {slot?.venue||""}</span></div><div className="attendance-list">{participants.map(p=>{const a=attendance.find(x=>x.schedule_id===slot.id&&x.participant_id===p.id);return <div className="attendance-row" key={p.id}><div><b>{p.name}</b><span>{p.team_name||"No team"} · {colleges.find(c=>c.id===p.college_id)?.name}</span></div><div className="att-actions"><button className={a?.status==="present"?"active present":""} onClick={()=>mark(p.id,"present")}><UserCheck size={16}/> Present</button><button className={a?.status==="absent"?"active absent":""} onClick={()=>mark(p.id,"absent")}><UserX size={16}/> Absent</button></div></div>})}{!participants.length&&<div className="empty large">No participating college has been assigned to this event yet. Ask the Super Admin to set the participation matrix.</div>}</div></main>}

function Login({auth,setAuth,error,login,back}){return <main className="login-page"><div className="login-copy"><span className="eyebrow">AQUA DESK / CONTROLLED ACCESS</span><h1>Enter the<br/><em>operations layer.</em></h1><p>Authorised accounts can view private college contacts, confirmation status and live attendance tools. Super Admin unlocks full editing.</p><button className="secondary" onClick={back}>Back to public view</button></div><form className="login-card" onSubmit={login}><div className="login-icon"><LockKeyhole/></div><h2>Sign in</h2><label>Email<input type="email" value={auth.email} onChange={e=>setAuth({...auth,email:e.target.value})} required placeholder="you@example.com"/></label><label>Password<input type="password" value={auth.password} onChange={e=>setAuth({...auth,password:e.target.value})} required placeholder="••••••••"/></label>{error&&<div className="error">{error}</div>}<button className="primary full">Enter AquaDesk <ArrowRight size={16}/></button></form></main>}

function LoginPrompt({setPage}){return <main className="section page"><div className="empty large"><LockKeyhole/><h2>Authorised area</h2><p>Sign in to access private operational information and attendance.</p><button className="primary" onClick={()=>setPage("login")}>Sign in</button></div></main>}

function AdminPanel({colleges,events,students,slots,participation,close,reload,toast}){
 const [tab,setTab]=useState("overview"),[editingCollege,setEditingCollege]=useState(null),[editingEvent,setEditingEvent]=useState(null),[editingParticipant,setEditingParticipant]=useState(null),[editingSlot,setEditingSlot]=useState(null),[showCollegeForm,setShowCollegeForm]=useState(false),[showEventForm,setShowEventForm]=useState(false),[showParticipantForm,setShowParticipantForm]=useState(false),[showSlotForm,setShowSlotForm]=useState(false);
 return <div className="admin-overlay"><div className="admin-panel"><div className="admin-top"><div><span className="eyebrow">SUPER ADMIN</span><h2>AquaDesk <em>Control Room</em></h2></div><button className="close" onClick={close}><X/></button></div><div className="admin-tabs">{[["overview","Overview",LayoutDashboard],["colleges","Colleges",Building2],["participants","Participants",Users],["events","Events",CalendarDays],["schedule","Schedule",Clock3],["participation","Participation",Settings2],["logs","Audit Logs",History]].map(([k,l,I])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}><I size={15}/>{l}</button>)}</div>
 {tab==="overview"&&<AdminOverview colleges={colleges} events={events} students={students} slots={slots}/>} 
 {tab==="colleges"&&<AdminColleges colleges={colleges} reload={reload} toast={toast} editing={editingCollege} setEditing={setEditingCollege} show={showCollegeForm} setShow={setShowCollegeForm}/>} 
 {tab==="participants"&&<AdminParticipants colleges={colleges} students={students} reload={reload} toast={toast} editing={editingParticipant} setEditing={setEditingParticipant} show={showParticipantForm} setShow={setShowParticipantForm}/>} 
 {tab==="events"&&<AdminEvents events={events} reload={reload} toast={toast} editing={editingEvent} setEditing={setEditingEvent} show={showEventForm} setShow={setShowEventForm}/>} 
 {tab==="schedule"&&<AdminSchedule events={events} slots={slots} reload={reload} toast={toast} editing={editingSlot} setEditing={setEditingSlot} show={showSlotForm} setShow={setShowSlotForm}/>} 
 {tab==="participation"&&<AdminParticipation colleges={colleges} events={events} participation={participation} reload={reload} toast={toast}/>} 
 {tab==="logs"&&<AdminLogs/>}
 </div></div>}

function AdminOverview({colleges,events,students,slots}){return <div><div className="stat-grid"><Stat icon={Building2} value={colleges.length} label="Colleges"/><Stat icon={Users} value={students.length} label="Participants"/><Stat icon={CalendarDays} value={events.length} label="Events"/><Stat icon={Clock3} value={slots.length} label="Schedule slots"/></div><div className="admin-info-grid"><div className="admin-info"><ShieldCheck/><div><b>Full control</b><span>Every college, participant, event, schedule slot and participation matrix is editable.</span></div></div><div className="admin-info"><Upload/><div><b>Logo uploads</b><span>Upload college and event logos directly into the AquaDesk asset bucket.</span></div></div><div className="admin-info"><ClipboardCheck/><div><b>Attendance</b><span>Authorised users can mark Present / Absent against each scheduled event slot.</span></div></div></div></div>}
function Stat({icon:I,value,label}){return <div className="stat-card"><I/><b>{value}</b><span>{label}</span></div>}

function AdminColleges({colleges,reload,toast,editing,setEditing,show,setShow}){const [form,setForm]=useState(emptyCollege),[contact,setContact]=useState(emptyContact),[status,setStatus]=useState("pending");useEffect(()=>{if(editing){setForm({...editing});supabase.from("college_contacts").select("*").eq("college_id",editing.id).maybeSingle().then(({data})=>setContact({...emptyContact,...data}));supabase.from("college_status").select("*").eq("college_id",editing.id).maybeSingle().then(({data})=>setStatus(data?.status||"pending"))}else{setForm(emptyCollege);setContact(emptyContact);setStatus("pending")}},[editing]);
 async function save(e){e.preventDefault();let collegeId=editing?.id;let res=editing?await supabase.from("colleges").update(form).eq("id",editing.id).select().single():await supabase.from("colleges").insert(form).select().single();if(res.error){toast(res.error.message);return}collegeId=res.data.id;await supabase.from("college_contacts").upsert({...contact,college_id:collegeId});await supabase.from("college_status").upsert({college_id:collegeId,status,note:null,confirmed_at:status==="confirmed"?new Date().toISOString():null});await supabase.rpc("write_audit",{p_action:editing?"update_college":"create_college",p_entity_type:"college",p_entity_id:collegeId,p_details:{name:form.name}});toast(editing?"College updated":"College created");setShow(false);setEditing(null);await reload()}
 async function remove(id){if(!confirm("Delete this college and its participants?"))return;const {error}=await supabase.from("colleges").delete().eq("id",id);toast(error?error.message:"College deleted");if(!error)await reload()}
 return <div className="admin-section"><AdminHeader title="College directory" action={()=>{setEditing(null);setShow(true)}}/><div className="manage-list">{colleges.map(c=><div key={c.id}><div className="list-main"><div className="mini-logo">{c.logo_url?<img src={c.logo_url} alt=""/>:<Building2/>}</div><div><b>{c.name}</b><span>{c.location||"No location"}</span></div></div><div className="row-actions"><button onClick={()=>{setEditing(c);setShow(true)}}><Edit3/></button><button className="danger" onClick={()=>remove(c.id)}><Trash2/></button></div></div>)}</div>{show&&<FormModal title={editing?"Edit college":"Add college"} close={()=>{setShow(false);setEditing(null)}}><form onSubmit={save}><LogoUpload value={form.logo_url} onChange={v=>setForm({...form,logo_url:v})} folder="colleges"/><div className="grid2"><Field label="College name" value={form.name} set={v=>setForm({...form,name:v})} required/><Field label="Location" value={form.location} set={v=>setForm({...form,location:v})}/></div><h4>Private contacts</h4><div className="grid2"><Field label="HOD name" value={contact.hod_name} set={v=>setContact({...contact,hod_name:v})}/><Field label="HOD phone" value={contact.hod_phone} set={v=>setContact({...contact,hod_phone:v})}/><Field label="HOD email" value={contact.hod_email} set={v=>setContact({...contact,hod_email:v})}/><Field label="Coordinator name" value={contact.coordinator_name} set={v=>setContact({...contact,coordinator_name:v})}/><Field label="Coordinator phone" value={contact.coordinator_phone} set={v=>setContact({...contact,coordinator_phone:v})}/><Field label="Coordinator email" value={contact.coordinator_email} set={v=>setContact({...contact,coordinator_email:v})}/></div><Field label="Private notes" value={contact.private_notes} set={v=>setContact({...contact,private_notes:v})} textarea/><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="denied">Denied</option></select></label><button className="primary full"><Save/> Save college</button></form></FormModal>}</div>}

function AdminParticipants({colleges,students,reload,toast,editing,setEditing,show,setShow}){const [form,setForm]=useState({name:"",team_name:"",college_id:""}),[contact,setContact]=useState({phone:"",email:""});useEffect(()=>{if(editing){setForm({name:editing.name,team_name:editing.team_name||"",college_id:editing.college_id});supabase.from("participant_contacts").select("*").eq("participant_id",editing.id).maybeSingle().then(({data})=>setContact({phone:data?.phone||"",email:data?.email||""}))}else{setForm({name:"",team_name:"",college_id:colleges[0]?.id||""});setContact({phone:"",email:""})}},[editing,colleges]);
 async function save(e){e.preventDefault();let res=editing?await supabase.from("participants_public").update(form).eq("id",editing.id).select().single():await supabase.from("participants_public").insert(form).select().single();if(res.error){toast(res.error.message);return}await supabase.from("participant_contacts").upsert({participant_id:res.data.id,...contact});await supabase.rpc("write_audit",{p_action:editing?"update_participant":"create_participant",p_entity_type:"participant",p_entity_id:res.data.id,p_details:{name:form.name}});toast(editing?"Participant updated":"Participant added");setShow(false);setEditing(null);await reload()}
 async function remove(id){if(!confirm("Delete participant?"))return;const {error}=await supabase.from("participants_public").delete().eq("id",id);toast(error?error.message:"Participant deleted");if(!error)await reload()}
 return <div className="admin-section"><AdminHeader title="Participants" action={()=>{setEditing(null);setShow(true)}}/><div className="manage-list">{students.map(s=><div key={s.id}><div className="list-main"><Users/><div><b>{s.name}</b><span>{colleges.find(c=>c.id===s.college_id)?.name||"Unknown college"} · {s.team_name||"No team"}</span></div></div><div className="row-actions"><button onClick={()=>{setEditing(s);setShow(true)}}><Edit3/></button><button className="danger" onClick={()=>remove(s.id)}><Trash2/></button></div></div>)}</div>{show&&<FormModal title={editing?"Edit participant":"Add participant"} close={()=>{setShow(false);setEditing(null)}}><form onSubmit={save}><div className="grid2"><Field label="Participant name" value={form.name} set={v=>setForm({...form,name:v})} required/><label>College<select value={form.college_id} onChange={e=>setForm({...form,college_id:e.target.value})} required>{colleges.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Field label="Team name" value={form.team_name} set={v=>setForm({...form,team_name:v})}/><Field label="Phone (private)" value={contact.phone} set={v=>setContact({...contact,phone:v})}/><Field label="Email (private)" value={contact.email} set={v=>setContact({...contact,email:v})}/></div><button className="primary full"><Save/> Save participant</button></form></FormModal>}</div>}

function AdminEvents({events,reload,toast,editing,setEditing,show,setShow}){const [form,setForm]=useState(emptyEvent);useEffect(()=>setForm(editing?{...editing}:emptyEvent),[editing]);async function save(e){e.preventDefault();const res=editing?await supabase.from("events").update(form).eq("id",editing.id):await supabase.from("events").insert(form);if(res.error){toast(res.error.message);return}const id=editing?.id||res.data?.[0]?.id; if(id)await supabase.rpc("write_audit",{p_action:editing?"update_event":"create_event",p_entity_type:"event",p_entity_id:id,p_details:{name:form.name}});toast(editing?"Event updated":"Event created");setShow(false);setEditing(null);await reload()}async function remove(id){if(!confirm("Delete event and its schedule?"))return;const {error}=await supabase.from("events").delete().eq("id",id);toast(error?error.message:"Event deleted");if(!error)await reload()}return <div className="admin-section"><AdminHeader title="Events & event details" action={()=>{setEditing(null);setShow(true)}}/><div className="manage-list">{events.map(e=><div key={e.id}><div className="list-main"><div className="mini-logo">{e.logo_url?<img src={e.logo_url} alt=""/>:<CalendarDays/>}</div><div><b>{e.name}</b><span>{e.current_heads?.split("\n")[0]?.split(" :")[0]?.split(" - ")[0]||"No heads added"}</span></div></div><div className="row-actions"><button onClick={()=>{setEditing(e);setShow(true)}}><Edit3/></button><button className="danger" onClick={()=>remove(e.id)}><Trash2/></button></div></div>)}</div>{show&&<FormModal title={editing?"Edit event":"Add event"} close={()=>{setShow(false);setEditing(null)}}><form onSubmit={save}><LogoUpload value={form.logo_url} onChange={v=>setForm({...form,logo_url:v})} folder="events"/><Field label="Event name" value={form.name} set={v=>setForm({...form,name:v})} required/><Field label="Short category / subtitle" value={form.description} set={v=>setForm({...form,description:v})} textarea/><Field label="Current heads / names (one per line)" value={form.current_heads} set={v=>setForm({...form,current_heads:v})} textarea/><Field label="Rules / details" value={form.rules} set={v=>setForm({...form,rules:v})} textarea/><button className="primary full"><Save/> Save event</button></form></FormModal>}</div>}

function AdminSchedule({events,slots,reload,toast,editing,setEditing,show,setShow}){const [form,setForm]=useState(emptySlot);useEffect(()=>setForm(editing?{...editing,event_id:editing.event_id||""}:{...emptySlot,event_id:events[0]?.id||""}),[editing,events]);async function save(e){e.preventDefault();const payload={...form,event_name:events.find(x=>x.id===form.event_id)?.name||""};delete payload.id;const res=editing?await supabase.from("event_schedule").update(payload).eq("id",editing.id):await supabase.from("event_schedule").insert(payload);if(res.error){toast(res.error.message);return}toast(editing?"Schedule updated":"Schedule added");setShow(false);setEditing(null);await reload()}async function remove(id){if(!confirm("Delete schedule entry?"))return;const {error}=await supabase.from("event_schedule").delete().eq("id",id);toast(error?error.message:"Schedule deleted");if(!error)await reload()}return <div className="admin-section"><AdminHeader title="Official schedule" action={()=>{setEditing(null);setShow(true)}}/><div className="manage-list">{slots.map(s=><div key={s.id}><div className="list-main"><Clock3/><div><b>{s.event_date} · {fmtTime(s.start_time)} {s.end_time?`— ${fmtTime(s.end_time)}`:"Onwards"}</b><span>{s.event_name} · {s.venue}</span></div></div><div className="row-actions"><button onClick={()=>{setEditing(s);setShow(true)}}><Edit3/></button><button className="danger" onClick={()=>remove(s.id)}><Trash2/></button></div></div>)}</div>{show&&<FormModal title={editing?"Edit schedule entry":"Add schedule entry"} close={()=>{setShow(false);setEditing(null)}}><form onSubmit={save}><div className="grid2"><label>Event<select value={form.event_id} onChange={e=>setForm({...form,event_id:e.target.value})}>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><Field label="Date" type="date" value={form.event_date} set={v=>setForm({...form,event_date:v})} required/><Field label="Start time" type="time" value={form.start_time} set={v=>setForm({...form,start_time:v})} required/><Field label="End time (blank = onwards)" type="time" value={form.end_time||""} set={v=>setForm({...form,end_time:v})}/><Field label="Venue" value={form.venue} set={v=>setForm({...form,venue:v})} required/></div><button className="primary full"><Save/> Save schedule</button></form></FormModal>}</div>}

function AdminParticipation({colleges,events,participation,reload,toast}){const [eventId,setEventId]=useState(events[0]?.id||"");useEffect(()=>{if(!eventId&&events[0])setEventId(events[0].id)},[events,eventId]);const map=new Map(participation.filter(x=>x.event_id===eventId).map(x=>[x.college_id,x]));async function toggle(college){const current=map.get(college.id);const value=!current?.participating;const {error}=await supabase.from("event_college_participation").upsert({event_id:eventId,college_id:college.id,participating:value,updated_at:new Date().toISOString()},{onConflict:"event_id,college_id"});toast(error?error.message:`${college.name}: ${value?"participating":"removed"}`);if(!error){await supabase.rpc("write_audit",{p_action:"update_event_participation",p_entity_type:"event",p_entity_id:eventId,p_details:{college_id:college.id,participating:value}});await reload()}}return <div className="admin-section"><AdminHeader title="College ↔ event participation"/><label>Choose event<select value={eventId} onChange={e=>setEventId(e.target.value)}>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><div className="participation-grid">{colleges.map(c=>{const on=map.get(c.id)?.participating;return <button className={on?"participating":""} key={c.id} onClick={()=>toggle(c)}><div className="mini-logo">{c.logo_url?<img src={c.logo_url} alt=""/>:<Building2/>}</div><div><b>{c.name}</b><span>{on?"Participating":"Not participating"}</span></div>{on?<CheckCircle2/>:<XCircle/>}</button>})}</div></div>}

function AdminLogs(){const [logs,setLogs]=useState([]);useEffect(()=>{supabase.from("audit_logs").select("*").order("created_at",{ascending:false}).limit(100).then(({data})=>setLogs(data||[]))},[]);return <div className="admin-section"><AdminHeader title="Audit history"/><div className="logs">{logs.map(l=><div key={l.id}><History/><div><b>{l.action}</b><span>{l.entity_type} · {l.entity_id||"—"}</span></div><small>{new Date(l.created_at).toLocaleString()}</small></div>)}{!logs.length&&<div className="empty">No audit entries yet.</div>}</div></div>}

function AdminHeader({title,action}){return <div className="admin-section-head"><div><span className="eyebrow">MANAGE</span><h3>{title}</h3></div>{action&&<button className="primary small" onClick={action}><Plus/> Add</button>}</div>}
function Field({label,value,set,textarea,type="text",required=false}){return <label>{label}{textarea?<textarea value={value||""} onChange={e=>set(e.target.value)} required={required}/>:<input type={type} value={value||""} onChange={e=>set(e.target.value)} required={required}/>}</label>}
function FormModal({title,close,children}){return <div className="overlay"><div className="modal form-modal"><button className="close" onClick={close}><X/></button><span className="eyebrow">AQUA DESK EDITOR</span><h2>{title}</h2>{children}</div></div>}
function LogoUpload({value,onChange,folder}){const [busy,setBusy]=useState(false);async function upload(e){const file=e.target.files?.[0];if(!file)return;if(file.size>3*1024*1024){alert("Logo must be under 3 MB");return}setBusy(true);const ext=file.name.split(".").pop();const path=`${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from("aquadesk-assets").upload(path,file,{upsert:false});if(error){alert(error.message)}else{const {data}=supabase.storage.from("aquadesk-assets").getPublicUrl(path);onChange(data.publicUrl)}setBusy(false)}return <div className="upload-box">{value?<img src={value} alt="logo preview"/>:<div><Upload/><span>No logo uploaded</span></div>}<label className="upload-button">{busy?<RefreshCw className="spin"/>:<Upload/>}{busy?"Uploading…":"Upload logo"}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={upload}/></label></div>}

function AppErrorBoundary(){return null}

createRoot(document.getElementById("root")).render(<App/>);
